name: creamy_field
description: Rich Text Editing Field & other components with rich text, selection toolbar & syntax highlight support. Useful in Rich text editors.
version: 0.4.0
homepage: https://github.com/predatorx7/snake_code/tree/packages/creamy_field/packages/creamy_field

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_highlighter: ^0.1.0+1
  highlighter: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
